### ISSUE TITLE
Upgrade Resilio Sync

### ISSUE THREAD

**Issue by tobiasfiechter** [yangxuan8282/docker-image#1]
Hi, is it possible to upgrade Resilio Sync to a newer version. What exactly does
`ENV RESILIO_VERSION=2.4.4`
 do?

Thnaks for the great work!

**Comment by yangxuan8282** [comment]
I have updated Resilio Sync to 2.5.2, it should be the latest version.

`ENV RESILIO_VERSION=2.4.4` in previous Dockerfile is just environment variables, actually have nothing to do with image, but you can create badge with it from microbadger.com, like this:

[![](https://images.microbadger.com/badges/version/yangxuan8282/rpi-resilio-sync.svg)](https://microbadger.com/images/yangxuan8282/rpi-resilio-sync "Get your own version badge on microbadger.com")

By the way, with previous version Dockerfile you can create latest Sync, because the url is  permanent link ( I guess ).

**Comment by tobiasfiechter** [comment]
Thank you so much for answering! I also thought it is a permalink to the latest version. But when I check on the Resilio Web UI it says it's Version 2.4.4 hm.
